import type { TranspileResult } from "@fearless/aot-transpiler";

export interface CollectedSql {
  /** All unique statements across all handlers, deduped by key. */
  readonly statements: ReadonlyMap<string, string>;
  /**
   * Distinct handle `registeredName` values (e.g. `"primary"`) referenced
   * across all async handlers. These are the keys used for
   * `handles.sql.get(registeredName)` in generated Rust.
   *
   * Note: statement key prefixes use `variableName` (e.g. `db_<hash>`), which
   * may differ from `registeredName` (e.g. `"primary"`). This field tracks
   * `registeredName` from `TranspileResult.registeredHandleNames`.
   */
  readonly registeredHandleNames: readonly string[];
}

/**
 * Collect SQL statements from all transpiled async handlers. Deduplicates
 * identical (key, sql) pairs across handlers. Throws on key collision with
 * conflicting SQL text (indicates a hash collision — vanishingly rare).
 */
export function collectSql(
  results: readonly { transpile: TranspileResult }[],
): CollectedSql {
  const statements = new Map<string, string>();
  const registeredNames = new Set<string>();

  for (const r of results) {
    const { kind, statements: stmts, registeredHandleNames } = r.transpile;
    if (kind !== "async") continue;

    for (const [key, sql] of stmts) {
      const existing = statements.get(key);
      if (existing != null && existing !== sql) {
        throw new Error(
          `Statement key collision: "${key}" maps to two different SQL texts. ` +
            `Hash collision in makeStatementKey? Got:\n  ${existing}\nvs\n  ${sql}`,
        );
      }
      statements.set(key, sql);
    }

    for (const name of registeredHandleNames) {
      registeredNames.add(name);
    }
  }

  return {
    statements,
    registeredHandleNames: [...registeredNames].sort(), // sorted for deterministic output
  };
}

/**
 * Generate Rust source containing:
 *   - A static `phf::Map<&'static str, &'static str> STATEMENTS`
 *   - A `pub fn register_handles(pool: Arc<Pool>) -> HandleRegistry`
 *
 * Returns an empty string when there are no statements (no async SQL handlers).
 * The CLI writes the output to `rust-core/src/aot/registry_init.rs`.
 */
export function emitRegistryInitRust(collected: CollectedSql): string {
  if (collected.statements.size === 0) {
    return "";
  }

  const stmtEntries = [...collected.statements.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `    ${rustStr(k)} => ${rustStr(v)},`)
    .join("\n");

  const handleInserts = collected.registeredHandleNames
    .map(
      (name) =>
        `    registry.register_sql(${rustStr(name)}, std::sync::Arc::new(crate::aot::handles::SqlHandle::new(${rustStr(name)}, pool.clone(), &STATEMENTS)));`,
    )
    .join("\n");

  return `// AUTO-GENERATED by fearless build. Do not edit — regenerated on every build.

#![cfg(all(feature = "pg-handles", feature = "aot-handlers"))]

use std::sync::Arc;
use deadpool_postgres::Pool;

pub static STATEMENTS: phf::Map<&'static str, &'static str> = phf::phf_map! {
${stmtEntries}
};

pub fn register_handles(pool: Arc<Pool>) -> crate::aot::handles::HandleRegistry {
    let mut registry = crate::aot::handles::HandleRegistry::new();
${handleInserts}
    registry
}
`;
}

function rustStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
