import { test } from "node:test";
import assert from "node:assert/strict";
import { compileApp, formatBuildReport } from "../src/index.js";

// ============================================================================
// Helpers
// ============================================================================

function compile(source: string) {
  return compileApp({ source });
}

// ============================================================================
// Discovery
// ============================================================================

test("discovers a single AOT-eligible handler", () => {
  const result = compile(`
    const app = new App();
    app.get("/users/:id", (ctx) => ctx.json({ id: ctx.params.id }));
  `);
  assert.equal(result.summary.total, 1);
  assert.equal(result.summary.aot, 1);
  assert.equal(result.summary.bun, 0);
  const route = result.routes[0];
  assert.ok(route);
  assert.equal(route.kind, "aot");
});

test("falls back to Bun for async handlers", () => {
  const result = compile(`
    app.get("/u/:id", async (ctx) => {
      const u = await db.find(ctx.params.id);
      return ctx.json(u);
    });
  `);
  assert.equal(result.summary.aot, 0);
  assert.equal(result.summary.bun, 1);
  const route = result.routes[0];
  assert.ok(route && route.kind === "bun");
  if (route.kind === "bun") {
    const ruleIds = route.reason.reasons.map((r) => r.rule);
    assert.ok(ruleIds.includes("no-await"));
  }
});

test("discovers template routes (app.text / app.json)", () => {
  const result = compile(`
    app.text("/plaintext", "Hello, World!");
    app.json("/json", { message: "Hello, World!" });
  `);
  assert.equal(result.summary.template, 2);
  assert.equal(result.summary.aot, 0);
  assert.equal(result.summary.bun, 0);
});

test("mixed app — AOT + Bun + template", () => {
  const result = compile(`
    app.text("/healthz", "ok");
    app.get("/u/:id", (ctx) => ctx.json({ id: ctx.params.id }));
    app.post("/u", async (ctx) => { const b = await ctx.body(); return ctx.json(b); });
  `);
  assert.equal(result.summary.aot, 1);
  assert.equal(result.summary.bun, 1);
  assert.equal(result.summary.template, 1);
  assert.equal(result.summary.total, 3);
});

test("handler reference (named function) falls back to Bun", () => {
  const result = compile(`
    function myHandler(ctx) { return ctx.json({}); }
    app.get("/x", myHandler);
  `);
  assert.equal(result.summary.bun, 1);
});

test("ignores app.get with non-string path", () => {
  const result = compile(`
    app.get(somePath, (ctx) => ctx.json({}));
  `);
  // We require a literal path to register the route; non-literal is ignored.
  assert.equal(result.summary.total, 0);
});

// ============================================================================
// Output shape
// ============================================================================

test("rustSource includes header + use line + handler fn", () => {
  const result = compile(`
    app.get("/u/:id", (ctx) => ctx.json({ id: ctx.params.id }));
  `);
  assert.match(result.rustSource, /Auto-generated by @fearless\/aot-build/);
  assert.match(result.rustSource, /use crate::aot::runtime as aot_runtime;/);
  assert.match(result.rustSource, /use crate::aot::AotRouteTable;/);
  assert.match(result.rustSource, /pub fn handler_/);
  assert.match(result.rustSource, /pub fn register\(table: &mut AotRouteTable\)/);
  assert.match(result.rustSource, /table\.add\("GET", "\/u\/:id", handler_/);
});

test("rustSource is empty when no AOT routes", () => {
  const result = compile(`
    app.text("/x", "hi");
    app.post("/y", async (ctx) => ctx.json(await ctx.body()));
  `);
  assert.equal(result.rustSource, "");
});

test("dispatch manifest entries match discovered routes", () => {
  const result = compile(`
    app.get("/a", (ctx) => ctx.json({ a: 1 }));
    app.text("/b", "bee");
    app.post("/c", async (ctx) => ctx.json({}));
  `);
  assert.equal(result.dispatchManifest.length, 3);
  const aot = result.dispatchManifest.find((d) => d.kind === "aot");
  const tmpl = result.dispatchManifest.find((d) => d.kind === "template");
  const bun = result.dispatchManifest.find((d) => d.kind === "bun");
  assert.ok(aot && aot.fnName != null);
  assert.equal(tmpl?.path, "/b");
  assert.equal(bun?.path, "/c");
});

test("AOT fnNames are unique across routes", () => {
  const result = compile(`
    app.get("/a", (ctx) => ctx.json({ a: 1 }));
    app.get("/b", (ctx) => ctx.json({ b: 2 }));
    app.get("/c", (ctx) => ctx.json({ c: 3 }));
  `);
  const fnNames = new Set(
    result.dispatchManifest.filter((d) => d.kind === "aot").map((d) => d.fnName)
  );
  assert.equal(fnNames.size, 3);
});

// ============================================================================
// Report formatting
// ============================================================================

test("formatBuildReport produces a one-line-per-route summary", () => {
  const result = compile(`
    app.get("/a", (ctx) => ctx.json({}));
    app.text("/b", "x");
    app.post("/c", async (ctx) => ctx.json({}));
  `);
  const report = formatBuildReport(result);
  assert.match(report, /Discovered 3 routes/);
  assert.match(report, /✅ GET .*\/a/);
  assert.match(report, /📄 GET .*\/b/);
  assert.match(report, /⚠️.*POST .*\/c/);
});

test("formatBuildReport mentions the blocking rule for Bun-fallback routes", () => {
  const result = compile(`
    app.get("/x", async (ctx) => { await foo(); return ctx.json({}); });
  `);
  const report = formatBuildReport(result);
  assert.match(report, /no-await/);
});
