// Auto-generated by @fearless/aot-build. Do not edit — regenerated on every `fearless build`.
// The Rust runtime contract lives in `crate::aot::runtime` (alias `aot_runtime` for short).
use crate::aot::runtime as aot_runtime;
use crate::aot::AotRouteTable;

pub fn handler_0_template__plaintext(req: &aot_runtime::AotRequest, out: &mut Vec<u8>) {
    // static response — bytes computed at compile time
    out.extend_from_slice(b"HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 13\r\nConnection: keep-alive\r\n\r\nHello, World!");
}

pub fn handler_1_template__json(req: &aot_runtime::AotRequest, out: &mut Vec<u8>) {
    // static response — bytes computed at compile time
    out.extend_from_slice(b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 27\r\nConnection: keep-alive\r\n\r\n{\"message\":\"Hello, World!\"}");
}

pub fn handler_2__echo__name(req: &aot_runtime::AotRequest, out: &mut Vec<u8>) {
    // dynamic response — body length computed at runtime
    let mut body: Vec<u8> = Vec::with_capacity(64);
    body.extend_from_slice(b"{");
    body.extend_from_slice(b"\"hello\":");
    body.extend_from_slice(b"\"");
    aot_runtime::write_json_string(&mut body, req.param("name"));
    body.extend_from_slice(b"\"");
    body.extend_from_slice(b"}");
    out.extend_from_slice(b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nConnection: keep-alive\r\nContent-Length: ");
    aot_runtime::write_decimal(out, body.len());
    out.extend_from_slice(b"\r\n\r\n");
    out.extend_from_slice(&body);
}

pub fn handler_3__config(req: &aot_runtime::AotRequest, out: &mut Vec<u8>) {
    // static response — bytes computed at compile time
    out.extend_from_slice(b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 222\r\nConnection: keep-alive\r\n\r\n{\"service\":\"fearless\",\"version\":\"0.3.0\",\"features\":{\"aot\":true,\"templates\":true,\"hooks\":true},\"limits\":{\"maxBodyBytes\":10485760,\"maxConnections\":65535},\"endpoints\":{\"health\":\"/healthz\",\"metrics\":\"/metrics\",\"docs\":\"/docs\"}}");
}

pub fn handler_4__access(req: &aot_runtime::AotRequest, out: &mut Vec<u8>) {
    if req.header("x-key") == "secret" {
        // static response — bytes computed at compile time
        out.extend_from_slice(b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 20\r\nConnection: keep-alive\r\n\r\n{\"access\":\"granted\"}");
        return;
    }
    // static response — bytes computed at compile time
    out.extend_from_slice(b"HTTP/1.1 401 Unauthorized\r\nContent-Type: application/json\r\nContent-Length: 18\r\nConnection: keep-alive\r\n\r\n{\"error\":\"denied\"}");
}

/// Register every AOT-compiled handler into the given route table.
/// Called once at server startup; `table` is then shared (read-only) across all workers.
pub fn register(table: &mut AotRouteTable) {
    table.add("GET", "/plaintext", handler_0_template__plaintext);
    table.add("GET", "/json", handler_1_template__json);
    table.add("GET", "/echo/:name", handler_2__echo__name);
    table.add("GET", "/config", handler_3__config);
    table.add("GET", "/access", handler_4__access);
}