// AUTO-GENERATED by fearless build. Do not edit — regenerated on every build.

#![cfg(all(feature = "pg-handles", feature = "aot-handlers"))]

use std::sync::Arc;
use deadpool_postgres::Pool;

pub static STATEMENTS: phf::Map<&'static str, &'static str> = phf::phf_map! {
    "db_06ecb1bb" => "SELECT id, randomnumber FROM world ORDER BY random() LIMIT 1",
};

pub fn register_handles(pool: Arc<Pool>) -> crate::aot::handles::HandleRegistry {
    let mut registry = crate::aot::handles::HandleRegistry::new();
    registry.register_sql("primary", std::sync::Arc::new(crate::aot::handles::SqlHandle::new("primary", pool.clone(), &STATEMENTS)));
    registry
}
